/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ovacostos_EquilibrioServiceNativo */

#ifndef _Included_com_example_ovacostos_EquilibrioServiceNativo
#define _Included_com_example_ovacostos_EquilibrioServiceNativo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ovacostos_EquilibrioServiceNativo
 * Method:    calcularPuntoEquilibrio
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_ovacostos_EquilibrioServiceNativo_calcularPuntoEquilibrio
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
