services:
  ova-costos:
    image: angiecobo/ova-costos:latest
    container_name: ova-costos
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - red-backend-app

